--- # mysql role: tasks

- name: install mysql server
  package: name=mysql-server state=installed
  register: mysql_install_result

- name: install mysql server dependencies
  package: name=MySQL-python state=installed

- name: start mysql server
  service: name=mysqld state=started enabled=yes
  when: mysql_install_result.changed

- name: Set root user password
  mysql_user: name=root
              host="localhost"
              password="{{ mysql_root_password }}"
              check_implicit_admin=yes
              login_user="root"
              login_password=""
              state=present
  when: mysql_install_result.changed

- name: delete anonymous users
  mysql_user: name=""
              host="{{ item }}"
              login_user="root"
              login_password="{{ mysql_root_password }}"
              state=absent
  with_items:
    - "{{ ansible_nodename }}"
    - localhost
  when: mysql_install_result.changed
